name: ci

on:
  push:
    branches: ["main", "devel/*"]
    tags:
      - 'v*.*'
  pull_request:
    branches: ["main", "devel/*"]
  release:
    types: [published]
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.ref }}-${{ github.event.pull_request.number || github.sha }}
  cancel-in-progress: true

jobs:
  check: # This job does nothing and is only used for the branch protection
    if: always()
    runs-on: ubuntu-latest
    steps:
      - run: echo 123
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: |
          echo "$GITHUB_CONTEXT"
  release:
    if: github.ref_type == 'tag'
    runs-on: ubuntu-latest
    needs:
      - check
    steps:
      - run: echo doing the release
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0 # we need tags for dynamic versioning
          show-progress: false

      - name: fail if not on a tag
        run: |
          git describe --tags --exact-match
