name: release
on:
  workflow_run:
    workflows: ["ci"]
    types: [completed]
    branches: ["main", "v*.*.*"]
jobs:
  publish:
    runs-on: ubuntu-latest
    if: github.event_name == 'workflow_dispatch' || (github.event.workflow_run.event == 'push' && github.event.workflow_run.conclusion == 'success')
    steps:
      # TODO: Add extra code to check that this runs only if current commit had a tag on it.
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github.event.workflow_run) }}
        run: |
          echo "$GITHUB_CONTEXT"

      - uses: actions/checkout@v4
        with:
          fetch-depth: 0 # we need tags for dynamic versioning
          show-progress: false

      - name: fail if not on a tag
        run: |
          git describe --tags --exact-match
